[#ftl]
[@b.head/]
[@b.toolbar title="校外考试"]
    bar.addItem("报名","signUp(document.stdOtherExamSignUpForm)");

    function signUp(form){
        bg.form.submit(form);
    }
[/@]
[@b.form name="stdOtherExamSignUpForm" action="!configList"]
    [@b.div style="margin-top:10px;text-align:center;font-weight:bold;"]校外考试报名记录[/@]
    [@b.grid items=signUps var="signUp" ]
        [@b.row]
            [@b.col title="报名科目"]${(signUp.subject.name)!}[/@]
            [@b.col title="报名费"][#if (signUp.feeOfSignUp)??]#{signUp.feeOfSignUp;m2M2}[/#if][/@]
            [@b.col title="考纲费"][#if (signUp.feeOfOutline)??]#{signUp.feeOfOutline;m2M2}[/#if][/@]
            [@b.col title="材料费"][#if (signUp.feeOfMaterial)??]#{signUp.feeOfMaterial;m2M2}[/#if][/@]
            [@b.col title="报名时间"]${(signUp.signUpAt?string("yyyy-MM-dd HH:mm:ss"))?if_exists}[/@]
            [@b.col title="考试校区"]${(signUp.campus.name)!}[/@]
        [/@]
    [/@]
    [@b.div style="margin-top:10px;text-align:center;font-weight:bold;"]校外考试成绩[/@]
    [@b.grid items=grades var="otherGrade"]
        [@b.row]
            [@b.col title="科目名称"]${(otherGrade.subject.name)!}[/@]
            [@b.col title="成绩"]${(otherGrade.score)!}[/@]
            [@b.col title="是否通过"]${(otherGrade.passed?string("通过","不通过"))!}[/@]
            [@b.col title="common.semester"]${otherGrade.semester.schoolYear}学年${otherGrade.semester.name}学期[/@]
        [/@]
    [/@]
[/@]
[@b.foot/]